### ISSUE TITLE
create quotation excel file for Thais Junior

### ISSUE THREAD

**Issue by robmagario** [robmagario/magario#4]
E esse tem?

Compre Direto da China com Taobao Agente Style
Mar 9th, 8:08pm
tem sim

Compre Direto da China com Taobao Agente Style
Mar 9th, 8:08pm
eh esse aqui

Compre Direto da China com Taobao Agente Style
Mar 9th, 8:08pm
http://item.taobao.com/item.htm?spm=a1z10.1-c.w5003-10208664986.10.bGlUkp&id=43610226916&scene=taobao_shop

Compre Direto da China com Taobao Agente Style
Mar 9th, 8:08pm
vai querer quantos desse?

Thais Junior
Mar 9th, 10:36pm
Quero 3 da foto de cima e 2 dessa última foto ok

**Comment by abbeythorley** [comment]
there is only one link?

On Mon, Mar 30, 2015 at 11:17 PM, Robson Hayashida <notifications@github.com
> wrote:

> Assigned #4 <https://github.com/robmagario/magario/issues/4> to
> @abbeythorley <https://github.com/abbeythorley>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robmagario/magario/issues/4#event-268597945>.
>



-- 
Abbey Thorley
Vice President of eCommerce Department
Magario International Company Limited
http://magario.com
P: (+852) 56355938
E: abbey.thorley@magario.com
Info: (+852)67379770 / info@magario.com
